Repository cyruzzo/AboveVTT, pull requests merged in 2022-04, with the labels that each got.

#374 mon image shows even when homebrew
  EncounterHandler.js
Labels: unsure

#395 Bugfix - for players owning tokens
  Token.js
  TokenMenu.js
Labels: bug

#359 Fixing the '24 minutes ago' bug
  MessageBroker.js
Labels: needwork
