Repository cyruzzo/AboveVTT, pull requests merged in 2023-04, with the labels that each got.

#1082 Prevent scene folder structure/buttons from retaining on scene swap.
  MessageBroker.js
  ScenesPanel.js
  Token.js
  TokensPanel.js
Labels: internal

#1083 Beta Fix - Tokens properly hide out of line of sight
  Fog.js
Labels: beta-regression

#1088 Add disable token vision/light as a scene option.
  Fog.js
  ScenesPanel.js
  Token.js
  TokenMenu.js
Labels: qol

#1084 Close text controller on tool swap, esc, clear all
  Text.js
Labels: qol

#1089 Allow players to end turn of `player accessible stats` tokens
  CombatTracker.js
  MessageBroker.js
Labels: qol

#1090 Feat - Add filter for `Show only monsters I have access to`
  TokensPanel.js
Labels: enhancement

#1095 Feat - Add `space` keybind for pausing players in DM view.
  KeypressHandler.js
Labels: qol

#1098 QoL - Smoother token movement when dropped and regrabbed in a short time to continue movement.
  Token.js
Labels: qol

#1099 Fix - Google drive/Dropbox links in audio weren't getting the correct audio source.
  audio/mixer.js
Labels: bug

#1101 Fix - initiative sometimes not updating to the correct number for players
  MessageBroker.js
Labels: bug

#1102 Feat/QoL - Search Audio Track Library; Sort tracklist alphabetically; Add Mixer Playlists; Edit and delete track from library on context menu; Allow time skipping by clicking on the progress bar of a track in the mixer
  abovevtt.css
  audio/mixer.js
  audio/track.js
  audio/ui.js
Labels: enhancement, qol

#1103 #1096 Fix combat tracker player sync
  CombatTracker.js
  MessageBroker.js
Labels: qol

#1106 Update manifest.json to fix font blocking
  manifest.json
Labels: internal

#1107 Fix temp hp bug
  Token.js
Labels: bug

#1108 Fix - clicks shoud go through locked tokens for players
  Token.js
Labels: bug

#1110 Fix - Only show shadow/line of sight layer when walls are on darkness 0 maps
  Fog.js
Labels: bug

#1113 Fix - Animated map audio, make sure a default volume is set so the DM doesn't have to change volume to get audio to play for players.
  CombatTracker.js
  Main.js
  MessageBroker.js
  audio/mixer.js
  audio/ui.js
Labels: bug

#1115 Fix - Another bug with height/width swap causing a diagnol shadow to appear on tall maps, and check token vision should be fully opaque.
  Fog.js
Labels: bug

#1118 Fix - Scaled scenes token movement with arrow keys, should no longer run into invisible walls or get caught unable to move.
  Fog.js
Labels: bug

#1119 Fix - Adjust light blur based on scene scale, this was revealing too much past walls on high scale maps.
  abovevtt.css
Labels: bug

#1114 QoL - default letter and number tokens to default have vision/light off
  built-in-tokens.js
Labels: qol

#1123 Beta Fix - Grid wizard being blacked out and 'shadow' auras on 0 darkness maps
  Fog.js
  ScenesPanel.js
  abovevtt.css
Labels: beta-regression

#1163 Delay removing click_pause on drag stop
  Token.js
Labels: internal
